// 참조용 타입 선언입니다. 실행 시에는 dist/GeOnDT.modules.js에서 import하십시오.
import * as three from "../../dist/types/three/build/three.module.js";
import { BufferGeometry, Material, Color, ColorRepresentation, Sphere, Object3D, Vector2, Raycaster, Vector3, Mesh, Quaternion, Frustum, ShaderMaterial, Euler, DataTexture, WebGLUtils, GLBufferAttribute, InstancedBufferAttribute, WebGLRenderTarget, MeshDepthMaterial, Matrix4, EventDispatcher, Scene, LineSegments, Points } from "../../dist/types/three/build/three.module.js";
import * as three_examples_jsm_lines_LineSegments2_js from "../../dist/types/three/examples/jsm/lines/LineSegments2.js";
import { LineSegments2 } from "../../dist/types/three/examples/jsm/lines/LineSegments2.js";
import GUI from "../../dist/types/three/examples/jsm/libs/lil-gui.module.min.js";
import * as three_examples_jsm_math_ConvexHull_js from "../../dist/types/three/examples/jsm/math/ConvexHull.js";
import * as three_examples_jsm_lines_LineSegmentsGeometry_js from "../../dist/types/three/examples/jsm/lines/LineSegmentsGeometry.js";

declare class U3dAppEventHandler {
    static EVENT: {
        MOUSEWHEEL: string;
        MOUSEMOVE: string;
        MOUSEDOWN: string;
        MOUSEUP: string;
        MOUSEOUT: string;
        TOUCHSTART: string;
        TOUCHMOVE: string;
        TOUCHEND: string;
        CLICK: string;
        DBLCLICK: string;
        KEYDOWN: string;
        KEYUP: string;
        START: string;
        CHANGE: string;
        END: string;
        RESIZE: string;
        CONTEXTRESTORE: string;
        CONTEXTLOST: string;
        SEARCHED: string;
        LOAD: string;
        LOADED: string;
        CONTEXTMENU: string;
        DISTANCE_2KM_LOADED: string;
        DISTANCE_4KM_LOADED: string;
        MODEL_LOADED: string;
        HEIGHT_LOADED: string;
        IMAGE_LOADED: string;
    };
    constructor(container: any, app: any);
    _initialized: boolean;
    _container: any;
    _app: any;
    _prevMoveX: any;
    _prevMoveY: any;
    _isMouseDown: boolean;
    _lBtnDown: boolean;
    _rBtnDown: boolean;
    _isDragging: boolean;
    _idMouseMove: any;
    _id: any;
    _preDownTime: number;
    _prevDownX: any;
    _prevDownY: any;
    _preMoveTime: number;
    _preMoveEvent: any;
    get listeners(): any;
    onchange(): void;
    createWorkingEndEvent(): void;
    isValidEventTarget(event: any): boolean;
    dispose(): boolean;
    isInitialized(): boolean;
    removeEvent(): void;
    _idMouseWheel: any;
    _idMouseDown: any;
    _idMouseUp: any;
    _idMouseOut: any;
    _idTouchStart: any;
    _idTouchMove: any;
    _idTouchEnd: any;
    _idMouseClick: any;
    _idMouseDBClick: any;
    _idContextLost: any;
    _idContextRestore: any;
    _idContextMenu: any;
    _idKeyDown: any;
    _idKeyUp: any;
    _idResize: any;
    addEvent(): void;
    onStart(e: any): void;
    onEnd(e: any): void;
    resetWorkingEndEvent(): void;
    click(u3dMouseEvent: any): void;
    dbclick(u3dMouseEvent: any): void;
    #private;
}

export type { U3dAppEventHandler };
